declare const styles: {
  readonly "actionBar": string;
  readonly "actionButton": string;
  readonly "actionButtonDanger": string;
  readonly "actionButtonIcon": string;
  readonly "audioBadge": string;
  readonly "audioCard": string;
  readonly "audioDuration": string;
  readonly "audioFilename": string;
  readonly "audioIcon": string;
  readonly "audioMeta": string;
  readonly "bodyWrapper": string;
  readonly "centeredContent": string;
  readonly "columnContainer": string;
  readonly "columnContainerOverflow": string;
  readonly "filterList": string;
  readonly "filterPill": string;
  readonly "filterPillActive": string;
  readonly "filterPillIcon": string;
  readonly "fullHeightRelative": string;
  readonly "fullSize": string;
  readonly "gifBadge": string;
  readonly "grid": string;
  readonly "headerContainer": string;
  readonly "mobileHeaderContainer": string;
  readonly "mobileHeaderContainerStandalone": string;
  readonly "scroller": string;
  readonly "scrollerFull": string;
  readonly "slate": string;
  readonly "slateDescription": string;
  readonly "slateIcon": string;
  readonly "slateTitle": string;
};
export = styles;

