port: 7880
log_level: info

rtc:
  node_ip: 10.0.0.157
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false

redis:
  address: "valkey:6379"
  username: ""
  password: ""
  db: 0
  use_tls: false

ingress:
  whip_base_url: "http://livekit-ingress:8080/whip"
  rtmp_base_url: "rtmp://livekit-ingress:1935/live"

webhook:
  api_key: fluxer
  urls:
    - http://api:8080/webhooks/livekit
