declare const styles: {
  readonly "actions": string;
  readonly "appAvatar": string;
  readonly "appAvatarImage": string;
  readonly "appAvatarPlaceholder": string;
  readonly "appCard": string;
  readonly "appList": string;
  readonly "appName": string;
  readonly "chevron": string;
  readonly "chevronExpanded": string;
  readonly "container": string;
  readonly "description": string;
  readonly "details": string;
  readonly "detailsRow": string;
  readonly "errorContainer": string;
  readonly "errorText": string;
  readonly "header": string;
  readonly "headerButton": string;
  readonly "left": string;
  readonly "loadingContainer": string;
  readonly "metaRow": string;
  readonly "metaText": string;
  readonly "scopeColumn": string;
  readonly "scopeDescription": string;
  readonly "scopeList": string;
  readonly "scopeName": string;
  readonly "scopeTag": string;
  readonly "scrollContainer": string;
  readonly "scrollerPadding": string;
  readonly "sectionLabel": string;
  readonly "textBlock": string;
  readonly "title": string;
  readonly "titleRow": string;
};
export = styles;

