declare const styles: {
  readonly "container": string;
  readonly "emptyDescription": string;
  readonly "emptyIcon": string;
  readonly "emptyState": string;
  readonly "emptyTitle": string;
  readonly "errorContainer": string;
  readonly "expandIcon": string;
  readonly "expandIconRotated": string;
  readonly "giftCard": string;
  readonly "giftCardActions": string;
  readonly "giftCardContent": string;
  readonly "giftCardHeader": string;
  readonly "giftDate": string;
  readonly "giftIcon": string;
  readonly "giftIconActive": string;
  readonly "giftIconImage": string;
  readonly "giftIconRedeemed": string;
  readonly "giftInfo": string;
  readonly "giftTitle": string;
  readonly "giftUrlSection": string;
  readonly "giftsList": string;
  readonly "iconMedium": string;
  readonly "loadingContainer": string;
  readonly "redeemButton": string;
  readonly "redeemButtonContainer": string;
  readonly "redeemForm": string;
  readonly "redeemInput": string;
  readonly "redeemedMessage": string;
  readonly "redeemedMessageText": string;
  readonly "sectionDescription": string;
  readonly "sectionDescriptionNoMargin": string;
  readonly "sectionHeader": string;
};
export = styles;

