declare const styles: {
  readonly "actions": string;
  readonly "closeButton": string;
  readonly "container": string;
  readonly "content": string;
  readonly "contentInner": string;
  readonly "contentNoPadding": string;
  readonly "contentStatic": string;
  readonly "divider": string;
  readonly "footer": string;
  readonly "footerNoBorder": string;
  readonly "handle": string;
  readonly "handleBar": string;
  readonly "header": string;
  readonly "headerAfter": string;
  readonly "headerAlignEnd": string;
  readonly "headerAlignStart": string;
  readonly "headerBorder": string;
  readonly "headerCenter": string;
  readonly "headerContent": string;
  readonly "headerGrid": string;
  readonly "headerPaddingLg": string;
  readonly "headerPaddingMd": string;
  readonly "headerPaddingSm": string;
  readonly "headerSafeArea": string;
  readonly "headerSlot": string;
  readonly "headerSlotLeading": string;
  readonly "headerSlotTrailing": string;
  readonly "root": string;
  readonly "section": string;
  readonly "subtitle": string;
  readonly "surfacePrimary": string;
  readonly "surfaceSecondary": string;
  readonly "surfaceTertiary": string;
  readonly "title": string;
};
export = styles;

