declare const styles: {
  readonly "actions": string;
  readonly "avatarActions": string;
  readonly "avatarColumn": string;
  readonly "avatarLarge": string;
  readonly "avatarPreview": string;
  readonly "channelTag": string;
  readonly "channelTagMobile": string;
  readonly "chevron": string;
  readonly "chevronExpanded": string;
  readonly "container": string;
  readonly "details": string;
  readonly "detailsRow": string;
  readonly "fieldGrow": string;
  readonly "fields": string;
  readonly "fieldsRow": string;
  readonly "fileInput": string;
  readonly "headerButton": string;
  readonly "iconSmall": string;
  readonly "label": string;
  readonly "left": string;
  readonly "metaRow": string;
  readonly "monoInput": string;
  readonly "name": string;
  readonly "textBlock": string;
  readonly "titleRow": string;
  readonly "truncate": string;
  readonly "urlWrapper": string;
};
export = styles;

