declare const styles: {
  readonly "categoryContainer": string;
  readonly "categoryDivider": string;
  readonly "categoryPermissions": string;
  readonly "categoryPermissionsDense": string;
  readonly "categoryPermissionsGrid": string;
  readonly "categoryTitle": string;
  readonly "overwriteToggle": string;
  readonly "overwriteToggleActions": string;
  readonly "overwriteToggleContent": string;
  readonly "overwriteToggleDense": string;
  readonly "overwriteToggleDescription": string;
  readonly "overwriteToggleTitle": string;
  readonly "overwriteToggleTitleDisabled": string;
  readonly "overwriteToggleTitleEnabled": string;
  readonly "permissionHelpLink": string;
  readonly "roleCategoryContainer": string;
  readonly "roleCategoryDivider": string;
  readonly "roleCategoryPermissions": string;
  readonly "roleCategoryPermissionsDense": string;
  readonly "roleCategoryPermissionsGrid": string;
  readonly "roleCategoryTitle": string;
  readonly "roleToggle": string;
  readonly "roleToggleDense": string;
  readonly "stateButton": string;
  readonly "stateButtonAllow": string;
  readonly "stateButtonDeny": string;
  readonly "stateButtonDisabled": string;
  readonly "stateButtonEnabled": string;
  readonly "stateButtonInactive": string;
  readonly "stateButtonNeutral": string;
  readonly "stateButtonsContainer": string;
  readonly "stateDivider": string;
  readonly "tooltipTriggerBlock": string;
  readonly "tooltipTriggerInline": string;
};
export = styles;

