declare const styles: {
  readonly "ariaMenu": string;
  readonly "backdrop": string;
  readonly "checkbox": string;
  readonly "checkboxChecked": string;
  readonly "checkboxIndicator": string;
  readonly "checkboxItem": string;
  readonly "contextMenu": string;
  readonly "contextMenuOverlay": string;
  readonly "danger": string;
  readonly "disabled": string;
  readonly "emojiSubmenuIcon": string;
  readonly "emojiSubmenuImg": string;
  readonly "emojiSubmenuNative": string;
  readonly "group": string;
  readonly "groupLabel": string;
  readonly "item": string;
  readonly "itemHint": string;
  readonly "itemIcon": string;
  readonly "itemLabel": string;
  readonly "itemLabelContainer": string;
  readonly "itemLabelText": string;
  readonly "itemShortcut": string;
  readonly "menuScroller": string;
  readonly "quickReactionItem": string;
  readonly "quickReactionsGroup": string;
  readonly "separator": string;
  readonly "submenuCaret": string;
  readonly "submenuPopover": string;
  readonly "submenuScroller": string;
};
export = styles;

