declare const styles: {
  readonly "categoryName": string;
  readonly "channelDetails": string;
  readonly "channelIcon": string;
  readonly "channelInfo": string;
  readonly "channelName": string;
  readonly "checkboxCell": string;
  readonly "container": string;
  readonly "desktopNotificationOptions": string;
  readonly "iconTertiary": string;
  readonly "mobileOverrideOptions": string;
  readonly "mobilePushSection": string;
  readonly "notificationSection": string;
  readonly "optionCategory": string;
  readonly "optionContainer": string;
  readonly "optionContent": string;
  readonly "overrideHeader": string;
  readonly "overrideItem": string;
  readonly "overridesHeader": string;
  readonly "overridesHeaderCell": string;
  readonly "overridesHeaderCellLeft": string;
  readonly "overridesHeaderCellMute": string;
  readonly "overridesSection": string;
  readonly "removeButton": string;
  readonly "removeIcon": string;
  readonly "section": string;
  readonly "sectionTitle": string;
  readonly "singleValueContainer": string;
  readonly "suppressSection": string;
};
export = styles;

