declare const styles: {
  readonly "buttonGroup": string;
  readonly "container": string;
  readonly "contentContainer": string;
  readonly "countryDialCode": string;
  readonly "countryFlag": string;
  readonly "countryOption": string;
  readonly "countryValue": string;
  readonly "description": string;
  readonly "footerText": string;
  readonly "formContainer": string;
  readonly "header": string;
  readonly "icon": string;
  readonly "iconContainer": string;
  readonly "inputGroup": string;
  readonly "phoneInputContainer": string;
  readonly "resendSection": string;
  readonly "resendText": string;
  readonly "selectLabel": string;
  readonly "stepBadge": string;
  readonly "stepRow": string;
  readonly "stepText": string;
  readonly "stepsCard": string;
  readonly "stepsContainer": string;
  readonly "tabActive": string;
  readonly "tabButton": string;
  readonly "tabContainer": string;
  readonly "tabInactive": string;
  readonly "title": string;
};
export = styles;

