declare const styles: {
  readonly "audioPlaceholder": string;
  readonly "clickableButton": string;
  readonly "clickableWrapper": string;
  readonly "fiveAttachmentContainer": string;
  readonly "gifIndicator": string;
  readonly "loading": string;
  readonly "loadingOverlay": string;
  readonly "mediaBlurred": string;
  readonly "mediaContainer": string;
  readonly "mediaImage": string;
  readonly "mediaImageHidden": string;
  readonly "mosaicContainer": string;
  readonly "mosaicContainerWrapper": string;
  readonly "mosaicExpiryBadge": string;
  readonly "mosaicExpiryBadgeContent": string;
  readonly "mosaicItem": string;
  readonly "mosaicItemLoading": string;
  readonly "nsfwOverlay": string;
  readonly "oneByOneGrid": string;
  readonly "oneByOneGridMosaic": string;
  readonly "oneByTwoDuoContainer": string;
  readonly "oneByTwoDuoItem": string;
  readonly "oneByTwoGrid": string;
  readonly "oneByTwoGridItem": string;
  readonly "oneByTwoLayoutThreeGrid": string;
  readonly "oneByTwoSoloItem": string;
  readonly "placeholderImage": string;
  readonly "playButton": string;
  readonly "playButtonOverlay": string;
  readonly "relativeWrapper": string;
  readonly "threeByThreeGrid": string;
  readonly "twoByOneGrid": string;
  readonly "twoByOneGridItem": string;
  readonly "twoByTwoGrid": string;
};
export = styles;

