declare const styles: {
  readonly "animatedEmoji": string;
  readonly "clamped": string;
  readonly "constrained": string;
  readonly "content": string;
  readonly "editPencilIcon": string;
  readonly "editableEmojiOnly": string;
  readonly "editableTextHover": string;
  readonly "editableWrapper": string;
  readonly "emojiPressable": string;
  readonly "emojiTooltipGuildIcon": string;
  readonly "emojiTooltipGuildName": string;
  readonly "emojiTooltipGuildRow": string;
  readonly "emojiTooltipSubtext": string;
  readonly "emojiTooltipTrigger": string;
  readonly "emojiTooltipVerifiedIcon": string;
  readonly "hiddenVisually": string;
  readonly "jumbo": string;
  readonly "nativeEmoji": string;
  readonly "placeholder": string;
  readonly "placeholderIcon": string;
  readonly "placeholderText": string;
  readonly "singleLine": string;
  readonly "staticEmoji": string;
  readonly "statusEmoji": string;
  readonly "statusEmojiWrapper": string;
  readonly "truncatedText": string;
};
export = styles;

