declare const styles: {
  readonly "avatar": string;
  readonly "card": string;
  readonly "cardWrapper": string;
  readonly "deleteButton": string;
  readonly "deleteButtonFloating": string;
  readonly "deleteIcon": string;
  readonly "gridAvatar": string;
  readonly "gridCard": string;
  readonly "gridCardWrapper": string;
  readonly "gridEmojiImage": string;
  readonly "gridEmojiWrapper": string;
  readonly "gridName": string;
  readonly "gridNameButton": string;
  readonly "gridNameText": string;
  readonly "header": string;
  readonly "headerCell": string;
  readonly "listCard": string;
  readonly "listCardWrapper": string;
  readonly "listEmoji": string;
  readonly "listEmojiImage": string;
  readonly "listName": string;
  readonly "listUploader": string;
  readonly "nameInlineEdit": string;
  readonly "nameInlineEditButton": string;
  readonly "nameInlineEditInput": string;
  readonly "renamePopout": string;
  readonly "renamePopoutActions": string;
  readonly "renamePopoutHeader": string;
  readonly "renamePopoutHint": string;
  readonly "renamePopoutTitle": string;
  readonly "unknownUser": string;
  readonly "username": string;
};
export = styles;

