declare const styles: {
  readonly "bioClamped": string;
  readonly "bioContainer": string;
  readonly "connectionBadge": string;
  readonly "connectionCard": string;
  readonly "connectionCardName": string;
  readonly "connectionCardNameRow": string;
  readonly "connectionCompactIcon": string;
  readonly "connectionDomainIcon": string;
  readonly "connectionExternalArrow": string;
  readonly "connectionExternalLink": string;
  readonly "connectionIcon": string;
  readonly "connectionTooltipContent": string;
  readonly "connectionsCompact": string;
  readonly "connectionsCompactSeparator": string;
  readonly "connectionsCompactWrapper": string;
  readonly "connectionsContainer": string;
  readonly "connectionsGrid": string;
  readonly "connectionsListMobile": string;
  readonly "connectionsTitle": string;
  readonly "iconSmall": string;
  readonly "membershipContainer": string;
  readonly "membershipDate": string;
  readonly "membershipDateText": string;
  readonly "membershipDates": string;
  readonly "membershipGuildIcon": string;
  readonly "membershipIcon": string;
  readonly "membershipTitle": string;
  readonly "rolesContainer": string;
  readonly "rolesEmpty": string;
  readonly "rolesHeader": string;
  readonly "rolesTitle": string;
  readonly "textChat": string;
  readonly "textXs": string;
  readonly "viewFullButton": string;
};
export = styles;

