declare const styles: {
  readonly "actionButton": string;
  readonly "actionButtons": string;
  readonly "actionIcon": string;
  readonly "actionIconButton": string;
  readonly "emptyState": string;
  readonly "emptyStateContent": string;
  readonly "emptyStateDescription": string;
  readonly "emptyStateIcon": string;
  readonly "emptyStateTextContainer": string;
  readonly "emptyStateTitle": string;
  readonly "endState": string;
  readonly "endStateContent": string;
  readonly "endStateDescription": string;
  readonly "endStateIcon": string;
  readonly "endStateTextContainer": string;
  readonly "endStateTitle": string;
  readonly "loadingState": string;
  readonly "loadingText": string;
  readonly "lostMessageIcon": string;
  readonly "lostMessageInner": string;
  readonly "lostMessageText": string;
  readonly "menuIcon": string;
  readonly "previewCard": string;
  readonly "previewCardMobile": string;
  readonly "scroller": string;
  readonly "scrollerMobile": string;
  readonly "topSpacer": string;
};
export = styles;

